fixing deploy ssh

diff --git a/.github/workflows/pantheon-deploy.yml b/.github/workflows/pantheon-deploy.yml
--- a/.github/workflows/pantheon-deploy.yml
+++ b/.github/workflows/pantheon-deploy.yml
@@ -144,9 +144,16 @@ jobs:
 
       - name: Add Pantheon SSH host keys
         run: |
+          set -x
           echo "Attempting to add Pantheon SSH host keys..."
+          whoami
+          pwd
+          echo "PANTHEON_SITE: ${{ secrets.PANTHEON_SITE }}"
+          ping -c 3 codeserver.dev.${{ secrets.PANTHEON_SITE }}.drush.in || echo "Ping failed. Check hostname and network."
+          nslookup codeserver.dev.${{ secrets.PANTHEON_SITE }}.drush.in
+          nc -vz codeserver.dev.${{ secrets.PANTHEON_SITE }}.drush.in 2222
           mkdir -p ~/.ssh
-          ssh-keyscan -H codeserver.dev.${{ secrets.PANTHEON_SITE }}.drush.in >> ~/.ssh/known_hosts
+          ssh-keyscan -H -p 2222 codeserver.dev.${{ secrets.PANTHEON_SITE }}.drush.in >> ~/.ssh/known_hosts
           echo "Contents of known_hosts:"
           cat ~/.ssh/known_hosts
           echo "Finished adding Pantheon SSH host keys."
